export const GET_NOTES_REQUEST = 'GET_NOTES_REQUEST';
export const GET_NOTES_SUCCESSFUL = 'GET_NOTES_SUCCESSFUL';
export const GET_NOTES_FAILURE = 'GET_NOTES_FAILURE';

export const UPDATE_NOTES_REQUEST = 'UPDATE_NOTES_REQUEST';
export const UPDATE_NOTES_SUCCESSFUL = 'UPDATE_NOTES_SUCCESSFUL';
export const UPDATE_NOTES_FAILURE = 'UPDATE_NOTES_FAILURE';
